### PR TITLE
Improve portability for non-x86 architectures

### PR DESCRIPTION
**Pull request by LTLA**
... where `_mm_prefetch` is not available. Also avoid looking for intrinsic headers or defining alignment macros when manual vectorization is turned off. Note that this requires both `NO_MANUAL_VECTORIZATION` and `NO_PREFETCH` to be defined for full portability.

### CODE REVIEW

**Comment by jlmelville** [comment]
Oh yeah, I also just removed all the multi-threading code, so you might need to merge back in those changes. Sorry about that.

**Comment by LTLA** [comment]
Regarding double negation: I guess I just followed Annoy's example of using `ifndef`s. I don't have much feeling about it either way. From an end-user's perspective, I suppose it makes it clear that the default is to use those features, and that people have to actively set `-DXXX` to turn them off.

**Comment by LTLA** [comment]
Also, is an explicit `cleanup` file actually necessary? It doesn't seem to do anything that wouldn't be automatically done by `R CMD INSTALL --preclean`.

**Comment by jlmelville** [comment]
The `cleanup` file was included from RcppAnnoy, cargo-cult style. It didn't seem to do any harm but I never looked at it. It can probably go.

Also, can 4632d78 be moved to a different PR, maybe even to https://github.com/nmslib/hnsw itself? I'd like to keep any changes to HNSW itself to just the addition of the preprocessor stuff. Also, there will be no ambiguity over who solely deserves the glory for that addition.

**Comment by LTLA** [comment]
Sure. And as I mentioned before, I think it would be a good idea for our pre-processor modifications to get into the original hnswlib as well. The ability to turn off the fancier optimizations would be helpful for  ensuring consistency across build systems. (Indeed, I recently ran into this exact same problem with Annoy, where the binaries produced by two different build systems were giving different results.)

If these modified preprocessor statements work okay here, I was thinking that you could just copy the files _en masse_ to hnswlib, pending @yurymalkov's approval. I'll just finish cleaning up some of the preprocessor checks before I revert 4632d78c424afdf5bb78030f75a6387c9a36bfdc for the time being.

**Comment by jlmelville** [comment]
I will certainly contribute the preprocessor changes as a PR upstream.

**Comment by jlmelville** [comment]
Once again, thanks for the contribution, @LTLA. I am about to lose power for the next 6 hours, but I will get this merged ASAP.

**Comment by LTLA** [comment]
I just finished up the PP statements. I think it is much cleaner now; the user-specified logic is all concentrated in `hnswlib.h`, which sets the `USE_AVX` and `USE_SSE` macros that do the actual work. (This also allows us to switch the `ifndef`s for `ifdefs`, which should make reading a little easier.)

One thing to note is that I expanded out the function definitions in `space_l2.h` and `space_ip.h` to avoid having to write a lot of nested `ifdef`s at the macro level. As such, there's a (very) little bit of code duplication but I think it makes the entire file easier to comprehend.

**Pull request merged**
