### PR TITLE
fixes #11

### LINKED ISSUE #11: Using multiple threads for index creation
`hnswlib` says that:

> Thread-safe with other `add_items` calls, but not with `knn_query`

Which means [this for loop](https://github.com/jlmelville/rcpphnsw/blob/9d608fb69aabaa0f87e124feab02e5945fe69a1e/src/hnsw.cpp#L115) should be quite trivial to wrap into threaded loop.

I will send PR implementing this with OpenMP.

### PR DESCRIPTION
**Pull request by dselivanov**
Please take a look, I'm open for discussion.

### CODE REVIEW

**Comment by jlmelville** [comment]
Thanks for having a go at this @dselivanov.

Some questions ("I don't know" is a perfectly good response to any of these!):

1. For CRAN submission, correct me if I'm wrong, but I though that we can't have more than one thread running in the tests?
2. What is the advantage of OpenMP for this versus just using `std::thread`? Is there a thread pool or some other improvements under the hood?
3. Are there platforms that don't have OpenMP versus an alternative like using RcppParallel? 
4. Are you sure it's ok to get at the innards of the R data? It looks like RcppAnnoy makes copies, e.g 
https://github.com/eddelbuettel/rcppannoy/blob/8e5e60cf63354fd7ad526701d3c76c38a7a2a2ee/src/annoy.cpp#L91 so is there a distinction I am missing here?

**Comment by dselivanov** [comment]
> 1. For CRAN submission, correct me if I'm wrong, but I though that we can't have more than one thread running in the tests?

Maximum 2 threads. I will update PR



> 2\. What is the advantage of OpenMP for this versus just using `std::thread`? Is there a thread pool or some other improvements under the hood?

- generally it is easier to write simple paralleled loops.
- OpenMP uses thread pool and can schedule jobs in a static/dynamic/guided way
- `std::thread` only available with C++ >= C++11, while OpenMP doesn't require C++11

> Are there platforms that don't have OpenMP versus an alternative like using RcppParallel?

Current CRAN Mac platform comes without OpenMP, but it is not very hard to add it for those who what they do - https://mac.r-project.org/openmp.  I personally used `RcppParallel` when OpenMP was not widely available but switched to the standard OpenMP long time. Again it is easier to parallilize simple loops with OpenMP compared to  RcppParallel. However for programs which require more complex thread communication RcppParallel and TBB might be better option. I haven't seen such scenarios in R world




> 4\. Are you sure it's ok to get at the innards of the R data? It looks like RcppAnnoy makes copies, e.g
>     https://github.com/eddelbuettel/rcppannoy/blob/8e5e60cf63354fd7ad526701d3c76c38a7a2a2ee/src/annoy.cpp#L91 so is there a distinction I am missing here?

Yes - you can work with primitive R data (numeric, integer) from threads. The most important is to not touch any R API from thread.
In the example they don't touch R data - they copy one std vector to another std vector. I assume this is for casting double to `T` (likely float).

**Comment by jlmelville** [comment]
Thanks for the explanations @dselivanov. It may take me a while before I can give this my full attention, and I'll need to spend some testing it, but I genuinely appreciate the PR and the discussion.

**Comment by SamGG** [comment]
Hi,
@dselivanov thanks for the improvements. In my hands, the building step goes from 50 sec down to 15 sec.
I did a few changes (see the PR to your repo).
That's great!

**Comment by SamGG** [comment]
I have just noticed that https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#OpenMP-support

> The performance of OpenMP varies substantially between platforms. The Windows implementation has substantial overheads, so is only beneficial if quite substantial tasks are run in parallel.

> Also, on Windows new threads are started with the default FPU control word, so computations done on OpenMP threads will not make use of extended-precision arithmetic which is the default for the main process.

**Comment by dselivanov** [comment]
> I have just noticed that https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#OpenMP-support

Unfortunately that's always will be the case with windows - certain features will be worse/missing/hard to implement. If you want to take full advantage of available hardware - use Linux. Or WSL2 on windows also worth to consider.

On a positive note, one need to measure described overheads. I suspect they are not too high.

**Comment by SamGG** [comment]
My main worry was about the FPU. Quite a strange behavior.

**Comment by dselivanov** [comment]
They are concerned about extended precision arithmetic. Never had issues with that. May be only some pathetic cases.

**Comment by SamGG** [comment]
@jlmelville just for information, this PR works nicely, quickly and safely on my Windows setup. I will do some more tests on accuracy. Currently, n_threads is not exposed to high level functions.

**Comment by jlmelville** [comment]
@SamGG thank you for testing the code. 

I do want to work on getting this merged, but I will be taking on the responsibility of maintaining it, and I (currently) have no experience or knowledge of OpenMP so it's not something I can take on lightly. I need to carve out a certain amount of spare time (and enthusiasm).

**Comment by LTLA** [comment]
Just going to add that OpenMP is pretty magical, a few `#pragma`s to an existing `for` loop and you're done. I've never used it in production code but it's been fun to play with as you can get it up and running on existing code with minor (or in some cases, no) refactoring; you can go straight to evaluating the performance benefit.

It is, in fact, so easy to set up that sometimes I forget that I have dependencies between my loop iterations and I get segfaults or race conditions from slapping `#pragma`s everywhere. This is probably the biggest issue; you need to be more careful that the loop contents are thread-safe. If they're not, the OpenMP-related code becomes a bit more complex to ensure that separate copies of any intermediate structures are generated for each thread, etc.

So, definitely worth learning at some point IMO. If `hnswlib` is as thread-safe as claimed, then this is a pretty nice and simple case to get your feet wet.

**Comment by jlmelville** [comment]
I am making very slow progress to merge this PR at the branch <https://github.com/jlmelville/rcpphnsw/tree/openmp>.

Is it possible for methods on the R-side to take default arguments? Currently, backwards compatibility with the API is broken because `p$addItems(data)` no longer works (I get a `could not find valid method` error). I would very much like to avoid breaking existing code. Creating an `addItemsParallel` method would be preferable.

**Comment by dselivanov** [comment]
> Is it possible for methods on the R-side to take default arguments?

I'm not sure how to do that with Rcpp Modules. 

BTW in the past I've had some hard to reproduce issues with Rcpp Modules. So I completely replaced them by using Rcpp external pointers and R6 classes.

**Comment by LTLA** [comment]
It should be possible to set the number of openMP threads via an environment variable - `OMP_NUM_THREADS`, I think it was. This would allow the specification to be passed in without changing the module function signature.

**Comment by dselivanov** [comment]
@LTLA that's true, but in this case you can't change number of threads in runtime, only beforehand

**Comment by LTLA** [comment]
Or maybe it was the `omp_set_num_threads()` function. [This](https://github.com/Bioconductor/ShortRead/blob/3616077f9f6f551cf031a3cff8dcfe17f02f7e2f/src/R_init_ShortRead.c) sets the number of threads globally for the entire session. Combined with `on.exit()`s in `hnsw_build()`, you can mimic argument passing directly to `addItems()`.

I had always wondered whether OpenMP would take the time to look up `OMP_NUM_THREADS` before every parallel region. I guess it doesn't. Probably just once during initialization and then any changes to the value are ignored.

**Comment by jlmelville** [comment]
Thanks for the replies @LTLA and @dselivanov. 

While I have you, I see that the Mac Travis CI is failing on Mac on the R 3.6.3 configurations (but not R 4.0.2) because its `clang` has no `-fopenmp` argument. Further research seems to suggest that the only solution for affected users is to install a newer `clang` via `brew`.

I this actually a weird travis thing, or a real problem for Mac users using R 3.x?

**Comment by dselivanov** [comment]
This is a bit complicated. CRAN R 3.6 binaries are compiled with openMP support, so when you install pkg from source, R macro suggest that OpenMP is available and passes `-fopenmp` flag to the compiler. But if compiler is default apple clang, then compilation fails since it doesn't support openmp.... Solution is to install clang6+ from https://cran.r-project.org/bin/macosx/tools/ and modify `~/.R/Makevars`... On other side unless i'm not mistaken everything should just work if pkg is installed from binaries from CRAN...

R 4.0 is built with default apple clang and openmp is disabled. But a concerned still can build pkg with openmp support - see [https://mac.r-project.org/openmp/](here)

**Comment by jlmelville** [comment]
I continue my glacial crawl to merging this PR.

There is a minor problem with `addItemNoCopy` not being thread safe (there's a `++cur_l` in there), but that just requires `cur_l` to be reset after adding all the items, like how the python bindings do it.

Adding a member variable and then introducing `set_num_threads`, like the Python bindings will also preserve backwards compatibility with the API.

**Comment by jlmelville** [comment]
For now, I have merged a version which uses `std::thread` rather than OpenMP in order to keep the Mac CI building.  I couldn't detect a speed difference between that and the OpenMP version with the testing I did (which was admittedly very limited).

@dselivanov I have added you as a contributor to the `DESCRIPTION`.

**Pull request merged**
